plugins:
  - jekyll-feed

exclude:
  - CNAME
  - README.md
  - .gitignore
  - vendor

markdown: kramdown

# drop .html extension
permalink: /:year/:month/:day/:title

# show all posts since events are scheduled for the future
future: true

url: https://chibug.org

# rss
feed:
  path: rss
title: "ChiBUG: Chicago Area BSD Users Group"
description: "ChiBUG: Chicago Area BSD Users Group"
url: "https://chibug.org"
author: "jcs"
